carla_client:
  carla_client_port: 2000
  fixed_delta_seconds: 0.05  # Float
  carla_connection_timeout: 10
  no_rendering_mode: False  # [true, false]  - On testing, i found this is faster than cv_render_debug
  synchronous_mode: True  # [true, false] - Keep it as it is
  cv_render_debug: False  # [true, false]

vehicle:
  vehicle_blueprint_id: "vehicle.tesla.model3"
  output_dir: "data/"
  warmup_ticks: 100
  ticks: 5000
  spectator_mode: True  # [true, false] - Keep it
  autopilot: True # [true, false]