carla_client:
  no_rendering_mode:False  # true, false
  carla_client_port:2000
  carla_connection_timeout:10
  synchronous_mode:true  # true, false
  fixed_delta_seconds:0.05  # Float
  
vehicle:
  spectator_mode:False  # true, false
  output_dir:"" 
  warmup_ticks:20
  vehicle_blueprint_id:""